name: 自动生成产品展示页 index.html

on:
  push:
    branches: [ main ]
    paths:
      - '**/products.json'
  workflow_dispatch:

jobs:
  generate-page:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆当前仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 初始化 Node 项目并安装依赖
        run: |
          npm init -y
          npm install axios

      - name: 下载构建脚本 build.js
        run: |
          curl -o build.js https://raw.githubusercontent.com/jkjj8899/main-site/main/scripts/build.js

      - name: 运行构建脚本生成 index.html
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GH_USERNAME: jkjj8899
        run: node build.js

      - name: 提交 index.html 到 product-site 仓库
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/jkjj8899/product-site.git temp-site
          cp index.html temp-site/index.html
          cd temp-site
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "自动生成产品展示页面" || echo "无变化"
          git push
