name: 自动推送到 Google Indexing API

on:
  workflow_dispatch:
  push:
    paths:
      - 'products.json'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: pip install google-auth requests

      - name: 生成密钥文件
        run: |
          echo "${{ secrets.GOOGLE_INDEXING_KEY }}" > key.json

      - name: 执行推送脚本
        run: |
          python .github/scripts/push_to_indexing.py
