name: 自动更新 sitemap.xml

on:
  push:
    paths:
      - 'products.json'
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆主仓库
        uses: actions/checkout@v3

      - name: 安装依赖
        run: pip install requests

      - name: 下载生成脚本
        run: curl -o gen_sitemap.py https://raw.githubusercontent.com/jkjj8899/main-site/main/scripts/gen_sitemap.py

      - name: 执行生成脚本
        run: python gen_sitemap.py

  deploy:
    runs-on: ubuntu-latest
    needs: generate
    steps:
      - name: 克隆 jkjj8899.github.io
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/jkjj8899/jkjj8899.github.io.git site
          mv sitemap.xml site/
          cd site
          git add sitemap.xml
          git commit -m "更新 sitemap.xml" || echo "No changes to commit"
          git push origin main
