name: 自动更新 sitemap.xml

on:
  push:
    paths:
      - 'products.json'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆 jkjj8899.github.io
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/jkjj8899/jkjj8899.github.io.git site

      - name: 下载 sitemap 生成脚本
        run: |
          curl -o gen_sitemap.py https://raw.githubusercontent.com/jkjj8899/main-site/main/scripts/gen_sitemap.py

      - name: 安装依赖
        run: pip install requests

      - name: 生成 sitemap.xml
        run: |
          python gen_sitemap.py
          ls -al sitemap.xml

      - name: 推送 sitemap.xml 到 jkjj8899.github.io
        run: |
          mv sitemap.xml site/
          cd site
          git add sitemap.xml
          git commit -m "自动更新 sitemap.xml" || echo "No changes"
          git push origin main
