name: 自动更新 sitemap.xml

on:
  push:
    paths:
      - 'products.json'
    branches:
      - main

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆主仓库
        uses: actions/checkout@v3

      - name: 安装依赖
        run: pip install requests

      - name: 生成 sitemap.xml
        run: |
          python <<EOF
          import json, requests
          from datetime import datetime

          products = requests.get(
            'https://raw.githubusercontent.com/jkjj8899/main-site/main/products.json'
          ).json()

          urls = [
            f"<url><loc>{p['link']}</loc><lastmod>{datetime.utcnow().date()}</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>"
            for p in products
          ]

          xml = f"""
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          {''.join(urls)}
          </urlset>""".strip()

          with open('sitemap.xml', 'w') as f:
              f.write(xml)
          EOF

      - name: 推送 sitemap.xml 到 jkjj8899.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_branch: main
          publish_dir: .
          destination_dir: .
          external_repository: jkjj8899/jkjj8899.github.io
          commit_message: 更新 sitemap.xml
